### ISSUE TITLE
Implement Manhattan Layout Optimiser

### ISSUE THREAD

**Issue by yashkotadia** [sunset1995/pytorch-layoutnet#12]
Could you please explain the steps that would be required to implement the Manhattan layout optimiser in the same repo?

**Comment by sunset1995** [comment]
Hi,
Borrow the similar idea, I have implemented a layout optimization using Gradient Ascent.
The process is described in [this section of README](https://github.com/sunset1995/pytorch-layoutnet#gradient-ascent-post-optimization) and the code is implemented in [pano_opt.py](https://github.com/sunset1995/pytorch-layoutnet/blob/master/pano_opt.py).
I achieve slightly better result and much more faster (30sec vs. less than 2sec) than official reported.
