### ISSUE TITLE
Unable replicate layout 3d viewer results; Random output

### ISSUE THREAD

**Issue by BillMatrix** [sunset1995/pytorch-layoutnet#17]
![screenshot 2019-01-27 12 14 46](https://user-images.githubusercontent.com/13478494/51806303-4059a400-222d-11e9-8fc7-6d8976e7cb5d.png)

Please see the output from the 3d viewer above. It is outputting some totally random noise for some reason. I'm running it on a macbook.

**Comment by sunset1995** [comment]
Hi,
Please provide the command you produce the result.
I just pushed a new commit which uses open3d for point cloud visualization.
I found open3d provide a better interface and portability (I have a hard time getting pptk work on my macbook).

**Comment by BillMatrix** [comment]
Let me test out your new visualizer. Thanks for the quick reply!

**Comment by BillMatrix** [comment]
It works now! Thanks!
