### ISSUE TITLE
Add torchfile to the dependencies

### ISSUE THREAD

**Issue by GalAvineri** [sunset1995/pytorch-layoutnet#9]
Hello :)  
I've just started trying to use your repository.  
I've done the following steps:  
1. I've built the directory tree as you guided.  
2. I've ran python torch2pytorch_data.py successfully  
3. I've ran python torch2pytorch_pretrained_weight.py --torch_pretrained ckpt/panofull_joint_box_pretrained.t7 --encoder ckpt/pre_full_encoder.pth --edg_decoder ckpt/pre_full_edg_decoder.pth --cor_decoder ckpt/pre_full_cor_decoder.pth  
which in turn resulted in the following error:  
Traceback (most recent call last):
  File "torch2pytorch_pretrained_weight.py", line 2, in <module>
    import torchfile
ImportError: No module named 'torchfile'

And the solution was to install torchfile :)

**Comment by ZHangZHengEric** [comment]
> Hello :)
> I've just started trying to use your repository.
> I've done the following steps:
> 
>     1. I've built the directory tree as you guided.
> 
>     2. I've ran python torch2pytorch_data.py successfully
> 
>     3. I've ran python torch2pytorch_pretrained_weight.py --torch_pretrained ckpt/panofull_joint_box_pretrained.t7 --encoder ckpt/pre_full_encoder.pth --edg_decoder ckpt/pre_full_edg_decoder.pth --cor_decoder ckpt/pre_full_cor_decoder.pth
>        which in turn resulted in the following error:
>        Traceback (most recent call last):
>        File "torch2pytorch_pretrained_weight.py", line 2, in 
>        import torchfile
>        ImportError: No module named 'torchfile'
> 
> 
> And the solution was to install torchfile :)

hi:
I have the same problem, do you know the solution?  thx.

**Comment by sunset1995** [comment]
I will solve it next week.

**Comment by GalAvineri** [comment]
@ZHangZHengEric yeah the solution was to run the following code:
```pip install torchfile```

@sunset1995 I've posted a pull request with the solution for your convenience

**Comment by GalAvineri** [comment]
The pull request has been merged :)

**Comment by zhangzheng-thu** [comment]
> @ZHangZHengEric yeah the solution was to run the following command in your terminal:
> `pip install torchfile`
> 
> @sunset1995 I've posted a pull request with the solution for your convenience

thx..O(∩_∩)O
